const albumLinks = [
  {
    album: "The Dark Side of the Moon",
    artist: "Pink Floyd",
    header: true,
    price: 28,
    like: false,
  },
  {
    album: "Abbey Road",
    artist: "The Beatles",
    header: true,
    price: 30,
    like: true,
  },
  {
    album: "OK Computer",
    artist: "Radiohead",
    header: false,
    price: 27,
    like: false,
  },
  {
    album: "In Rainbows",
    artist: "Radiohead",
    header: false,
    price: 22,
    like: true,
  },
  {
    album: "Paranoid",
    artist: "Black Sabbath",
    header: false,
    price: 29,
    like: false,
  },
  {
    album: "Nevermind",
    artist: "Nirvana",
    header: false,
    price: 26,
    like: false,
  },
  {
    album: "The New Abnormal",
    artist: "The Strokes",
    header: false,
    price: 19,
    like: false,
  },
  {
    album: "By The Way",
    artist: "Red Hot Chili Peppers",
    header: false,
    price: 24,
    like: false,
  },
  {
    album: "A Night at the Opera",
    artist: "Queen",
    header: false,
    price: 31,
    like: false,
  },
  {
    album: "Only by the Night",
    artist: "Kings of Leon",
    header: false,
    price: 23,
    like: false,
  },
  {
    album: "American Idiot",
    artist: "Green Day",
    header: false,
    price: 25,
    like: false,
  },
  {
    album: "Is This It",
    artist: "The Strokes",
    header: false,
    price: 20,
    like: false,
  },
  {
    album: "AM",
    artist: "Arctic Monkeys",
    header: true,
    price: 27,
    like: false,
  },
  {
    album: "Led Zeppelin IV",
    artist: "Led Zeppelin",
    header: false,
    price: 33,
    like: false,
  },
  {
    album: "Hotel California",
    artist: "Eagles",
    header: false,
    price: 32,
    like: false,
  },
  {
    album: "The Wall",
    artist: "Pink Floyd",
    header: false,
    price: 34,
    like: true,
  },
  {
    album: "Born to Run",
    artist: "Bruce Springsteen",
    header: false,
    price: 21,
    like: true,
  },
  {
    album: "Hunky Dory",
    artist: "David Bowie",
    header: false,
    price: 18,
    like: false,
  },
];

export default albumLinks;
export const token = import.meta.env.VITE_TOKEN;
